# Clippy configuration

# Cognitive complexity threshold
cognitive-complexity-threshold = 30

# Documentation requirements
missing-docs-in-crate-items = true

# Performance lints
too-many-arguments-threshold = 7
type-complexity-threshold = 250

# Style preferences
enum-variant-name-threshold = 3
single-char-binding-names-threshold = 4

# Allowed lints (use sparingly)
# allow = ["clippy::module_name_repetitions"]
