# Rust formatting configuration

# Basic formatting
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Function formatting
fn_args_layout = "Tall"
brace_style = "SameLineWhere"

# Control flow formatting
control_brace_style = "AlwaysSameLine"

# Comment formatting
normalize_comments = true
wrap_comments = true
comment_width = 80

# String formatting
format_strings = true

# Misc
newline_style = "Unix"
remove_nested_parens = true
use_small_heuristics = "Default"
