# Rust formatting configuration

# Basic formatting
max_width = 100
hard_tabs = false
tab_spaces = 4

# Misc (stable options only)
newline_style = "Unix"
remove_nested_parens = true
use_small_heuristics = "Default"
